# 工作流名称
name: Assemble Weapp Release

# 触发工作流程的事件
on:
  push:
    tags: [ v*, w* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# 工作流环境变量
env:
  # 小程序的appid
  WEAPP_ID: ${{ secrets.WEAPP_ID }}
  # 小程序的秘钥
  WEAPP_KEY: ${{ secrets.WEAPP_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}
      - name: Install Dependencies
        run: |
          pnpm i
      - name: Import Weapp Key
        run: echo "$WEAPP_KEY" | base64 --decode > key/private.appid.key
        env:
          WEAPP_KEY: ${{ env.WEAPP_KEY }}
      - name: Build Taro Playground Weapp
        run: |
          pnpm build:weapp -- --upload
        env:
          WEAPP_ID: ${{ env.WEAPP_ID }}
