# 工作流名称
name: Assemble Weapp Release

# 触发工作流程的事件
on:
  push:
    tags: [ v*, w* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# 工作流环境变量
env:
  # 小程序的appid
  WEAPP_ID: ${{ secrets.WEAPP_ID }}
  # 小程序的秘钥
  WEAPP_KEY: ${{ secrets.WEAPP_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules Folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: |
          pnpm i
      - name: Import Weapp Key
        run: echo "$WEAPP_KEY" | base64 --decode > key/private.appid.key
        env:
          WEAPP_KEY: ${{ env.WEAPP_KEY }}
      - name: Build Taro Playground Weapp
        run: |
          pnpm build:weapp -- --upload
        env:
          WEAPP_ID: ${{ env.WEAPP_ID }}
